In [1]:
import numpy as np

In [4]:
a = np.arange(18)

In [5]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [7]:
a = a.reshape(9,2)

In [8]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [9]:
a.shape

(9, 2)

In [10]:
b=np.array([45,8,58,5,965,885,85,85,7,4,8])

In [11]:
b

array([ 45,   8,  58,   5, 965, 885,  85,  85,   7,   4,   8])

In [12]:
np.argsort(b)

array([ 9,  3,  8,  1, 10,  0,  2,  6,  7,  5,  4], dtype=int32)

In [13]:
np.argmin(b)

9

In [14]:
np.argmax(b)

4